; PlatformIO Project Configuration File
;

[env:esp8266]
platform = espressif32
board = d1_mini
framework = arduino
monitor_speed = 115200
lib_deps = 
	paulstoffregen/OneWire@^2.3.5
	milesburton/DallasTemperature@^3.9.1
	bblanchon/ArduinoJson@^6.17.2
	knolleary/PubSubClient@^2.8
